backend:
  name: github
  repo: alecrsf/TecnicasML 
  branch: main
  site_domain: netlifycms-rmd-github.netlify.app

site_url: https://alecrsf.github.io/TecnicasML/

media_folder: "TecnicasML_files/"

collections:
  - name: "Rmd Pages"
    label: "Rmarkdown"
    format: "yaml-frontmatter"
    files:
      - label: "Index"
        name: "TecnicasML"
        file: "TecnicasML.Rmd"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "Markdown Pages"
    label: "markdown"
    files:
      - label: "readme"
        name: "readme"
        file: "README.md"
        fields:
          - {label: "Body", name: "body", widget: "markdown"}
          